export const SET_OPEN_SIDEBAR = 'SET_OPEN_SIDEBAR'
export const SET_EXPAND_SIDEBAR = 'SET_EXPAND_SIDEBAR'
export const SET_MOBILE_SIDEBAR = 'SET_MOBILE_SIDEBAR'
export const SET_OPEN_MOBILE_SIDEBAR = 'SET_OPEN_MOBILE_SIDEBAR'

export const SET_ROOMS = 'SET_ROOMS'
export const SET_ROOM = 'SET_ROOM'

export const ADD_MESSAGE = 'ADD_MESSAGE'
export const SELECT_MESSAGE = 'SELECT_MESSAGE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const SET_EDIT_STATUS = 'SET_EDIT_STATUS'
export const EDIT_MESSAGE = 'EDIT_MESSAGE'
export const ADD_FILE = 'ADD_FILE'
export const DELETE_FILE = 'DELETE_FILE'


export const SET_AUTH = 'SET_AUTH'
export const SET_PROFILE = 'SET_PROFILE'

export const SET_FETCHING = 'SET_FETCHING'

